### ISSUE TITLE
연습모드, 실전모드 header url 링크 버그

### ISSUE THREAD

**Issue by sumi-0011** [msdio/Tamago#235]
## 📌 이슈 설명
연습모드, 실전모드 header url 링크 잘못 연결됨 
### 🐠 체크리스트

-   [ ]
-   [ ]

### 🚴 이렇게 고쳐볼 수 있을 것 같아요
path.ts 파일에서 해당하는 url을 정확히 매칭시켜 수정할 예정

**Comment by msdio** [comment]
@sumi-0011 이건 제가 처리할게요~
