### ISSUE TITLE
카카오 로그인 안되는 오류

### ISSUE THREAD

**Issue by sumi-0011** [msdio/Tamago#305]
## 📌 이슈 설명
카카오톡 로그인 시도시, 오류가 뜨며 진행되지 않습니다

### 🐠 체크리스트

-   [ ] 
-   [ ]

### 🚴 이렇게 고쳐볼 수 있을 것 같아요
로컬환경과 실제 배포환경의 차이에서 발생한것 같아, 
env쪽 설정을 확인해보는게 좋을 것 같습니다. 

### 🍳 이런 환경에서 발생했어요

-   Device: Mac m1
-   OS: mac
-   Browser: Chrome
-   Version: 

### 📷 스크린샷
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/49177223/233842896-d2995d77-6f1a-4a90-853a-9cf2c89d18f9.png">

**Comment by msdio** [comment]
env 값의 문제인 것 같아요. 수정했는데 프로덕션 환경에서 한번만 다시 확인해봐주실수 있을까요?
